version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./scripts/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:rw
      - ./scripts/postgres/files.sql:/docker-entrypoint-initdb.d/files.sql:rw
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
  postgres_data: {}
