/**
 * File Router
 */
const FILE_ROUTER_SUT_FILE_RECORD_USE_CASE_THROWING_ERROR = Symbol(
  'FILE_ROUTER_SUT_FILE_RECORD_USE_CASE_THROWING_ERROR',
);
const FILE_ROUTER_SUT_FILE_DELETE_USE_CASE_THROWING_ERROR = Symbol(
  'FILE_ROUTER_SUT_FILE_DELETE_USE_CASE_THROWING_ERROR',
);

module.exports = {
  FILE_ROUTER_SUT_FILE_RECORD_USE_CASE_THROWING_ERROR,
  FILE_ROUTER_SUT_FILE_DELETE_USE_CASE_THROWING_ERROR,
};
