/**
 * File Record Use Case
 */
const FILE_RECORD_USE_CASE_WITH_NO_DEPENDENCY = Symbol(
  'FILE_RECORD_USE_CASE_WITH_NO_DEPENDENCY',
);
const FILE_RECORD_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY = Symbol(
  'FILE_RECORD_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY',
);
const FILE_RECORD_USE_CASE_HAS_INSERT_FILE_REPOSITORY_WITH_NO_INSERT = Symbol(
  'FILE_RECORD_USE_CASE_HAS_INSERT_FILE_REPOSITORY_WITH_NO_INSERT',
);
const FILE_RECORD_USE_CASE_SUT_INSERT_FILE_REPOSITORY_THROWING_ERROR = Symbol(
  'FILE_RECORD_USE_CASE_SUT_INSERT_FILE_REPOSITORY_THROWING_ERROR',
);

/**
 * File Delete Use Case
 */
const FILE_DELETE_USE_CASE_WITH_NO_DEPENDENCY = Symbol(
  'FILE_DELETE_USE_CASE_WITH_NO_DEPENDENCY',
);
const FILE_DELETE_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY = Symbol(
  'FILE_DELETE_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY',
);
const FILE_DELETE_USE_CASE_HAS_FILE_DELETE_ADAPTER_WITH_NO_DELETE = Symbol(
  'FILE_DELETE_USE_CASE_HAS_FILE_DELETE_ADAPTER_WITH_NO_DELETE',
);

module.exports = {
  FILE_RECORD_USE_CASE_WITH_NO_DEPENDENCY,
  FILE_RECORD_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY,
  FILE_RECORD_USE_CASE_HAS_INSERT_FILE_REPOSITORY_WITH_NO_INSERT,
  FILE_RECORD_USE_CASE_SUT_INSERT_FILE_REPOSITORY_THROWING_ERROR,
  FILE_DELETE_USE_CASE_WITH_NO_DEPENDENCY,
  FILE_DELETE_USE_CASE_WITH_EMPTY_OBJECT_AS_DEPENDENCY,
  FILE_DELETE_USE_CASE_HAS_FILE_DELETE_ADAPTER_WITH_NO_DELETE,
};
