/**
 * Insert File Repository
 */
const INSERT_FILE_REPOSITORY_WITH_NO_DEPENDENCY = Symbol(
  'INSERT_FILE_REPOSITORY_WITH_NO_DEPENDENCY',
);

module.exports = {
  INSERT_FILE_REPOSITORY_WITH_NO_DEPENDENCY,
};
